FROM apache/airflow:2.8.1-python3.11

USER root
COPY requirements-airflow.txt /tmp/requirements-airflow.txt
RUN pip install --no-cache-dir -r /tmp/requirements-airflow.txt

USER airflow
ENV PYTHONPATH=/opt/airflow/dags_repo
